### ISSUE TITLE
tmt plan lint: traceback

### ISSUE THREAD

**Issue by psklenar** [psss/tmt#121]
10:59 $ cat ci.fmf 
summary:
    Essential command line features
discover:
    - name: name_1_here
    how: fmf
    repository: "git://pkgs.devel.redhat.com/cgit/tests/bind"
execute:
    how: beakerlib
✔ ~/WTF/bind [rhel-8.2.0|…2] 
10:59 $ tmt plan lint
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fmf/base.py", line 316, in grow
    data = yaml.load(datafile, Loader=YamlLoader)
  File "/usr/lib64/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib64/python3.7/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib64/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib64/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib64/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib64/python3.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib64/python3.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/lib64/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python3.7/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "/home/psklenar/WTF/bind/ci.fmf", line 4, column 5
expected <block end>, but found '?'
  in "/home/psklenar/WTF/bind/ci.fmf", line 5, column 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tmt", line 11, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 763, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 716, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1136, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1136, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 955, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 554, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/tmt/cli.py", line 541, in lint
    for plan in context.obj.tree.plans():
  File "/usr/lib/python3.7/site-packages/tmt/base.py", line 498, in plans
    return [Plan(plan, run=run) for plan in self.tree.prune(
  File "/usr/lib/python3.7/site-packages/tmt/base.py", line 461, in tree
    self._tree = fmf.Tree(self._path)
  File "/usr/lib/python3.7/site-packages/fmf/base.py", line 85, in __init__
    self.grow(data)
  File "/usr/lib/python3.7/site-packages/fmf/base.py", line 319, in grow
    fullpath, error)))
fmf.utils.FileError: Failed to parse '/home/psklenar/WTF/bind/ci.fmf'
while parsing a block collection
  in "/home/psklenar/WTF/bind/ci.fmf", line 4, column 5
expected <block end>, but found '?'
  in "/home/psklenar/WTF/bind/ci.fmf", line 5, column 5

**Comment by psss** [comment]
Thanks for reporting this. Code updated to catch `FileError` exceptions from `fmf` as well.
