### ISSUE TITLE
tmt tests import -> traceback for missing RunFor

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#173]
I was missing `RunFor` in the Makefile and I got traceback.
Please make it nicer message instead and make sure **all** expectated values from Makefile are in try/except because they will be missing for someone :)

```python
Traceback (most recent call last):
  File "/home/lzachar/.virtualenvs/tmt/bin/tmt", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/lzachar/_important_/Gits/tmt/bin/tmt", line 11, in <module>
    tmt.cli.main()
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lzachar/_important_/Gits/tmt/tmt/cli.py", line 497, in import_
    path, makefile, nitrate, purpose, disabled)
  File "/home/lzachar/_important_/Gits/tmt/tmt/convert.py", line 135, in read
    r'^RunFor:\s*(.*)', testinfo, re.M).group(1).split()
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by psss** [comment]
@hegerj, would like to take this one?

**Comment by hegerj** [comment]
@psss sure
