### ISSUE TITLE
Traceback because of "No module named 'testcloud'"

### ISSUE THREAD

**Issue by happz** [psss/tmt#175]
```
bash-5.0$ rpm -q tmt
tmt-0.11-1.fc31.noarch
bash-5.0$ tmt
Traceback (most recent call last):
  File "/usr/bin/tmt", line 7, in <module>
    import tmt.cli
  File "/usr/lib/python3.7/site-packages/tmt/__init__.py", line 3, in <module>
    from tmt.base import Tree, Test, Plan, Story, Run
  File "/usr/lib/python3.7/site-packages/tmt/base.py", line 16, in <module>
    import tmt.steps.provision
  File "/usr/lib/python3.7/site-packages/tmt/steps/provision/__init__.py", line 11, in <module>
    from tmt.steps.provision import vagrant, localhost, podman, testcloud
  File "/usr/lib/python3.7/site-packages/tmt/steps/provision/testcloud.py", line 6, in <module>
    import testcloud.image
ModuleNotFoundError: No module named 'testcloud'
bash-5.0$ 
```

**Comment by thrix** [comment]
@happz this needs to be fixed on our side :) for now, but let's keep it here

**Comment by thrix** [comment]
we  need to install also `tmt-testcloud`

**Comment by happz** [comment]
I don't think it has to be **fixed** on our side - we can add a workaround. If I install the official `tmt` RPM and it crashes this way, I am **not** the one who's supposed to fix it ;)

**Comment by thrix** [comment]
@happz sorry, it has to be workaround on our side (for now) :)

**Comment by psss** [comment]
Yes, the minimal install is not working. Fixing this in #177.
