### ISSUE TITLE
beakerlib: libvirt.libvirtError: authentication unavailable: no polkit agent available to authenticate action 'org.libvirt.unix.manage'

### ISSUE THREAD

**Issue by junaruga** [psss/tmt#329]
This ticket comes from this ticket https://src.fedoraproject.org/tests/ruby/pull-request/1#comment-54647 at Fedora tests/ruby repository.

When running `tmt` command for the fmf file at https://src.fedoraproject.org/fork/pvalena/tests/ruby/tree/tmt , I got the error message `libvirt.libvirtError: authentication unavailable: no polkit agent available to authenticate action 'org.libvirt.unix.manage'`.

Do you have any idea to fix this error?

Thank you.

```
$ sudo dnf install tmt

$ sudo dnf install tmt-provision-virtual

$ git clone -b tmt https://src.fedoraproject.org/forks/pvalena/tests/ruby.git

$ cd ruby

$ pwd
/home/jaruga/fed/tests/ruby

$ tmt run -avv execute -h beakerlib
/var/tmp/tmt/run-003
Found 1 plan.

/plans/default
    discover
        how: fmf
        directory: /home/jaruga/git/pkg/fed/tests/ruby
        summary: 2 tests selected
            /run-basic-rails-application
            /systemtap-static-probes-in-ruby
    provision
        how: virtual
        image: fedora
        user: root
        memory: 2048 MB
        disk: 10 GB
        qcow: Fedora-Cloud-Base-32-1.6.x86_64.qcow2
        progress: downloading...
        name: gehKKKVPNmgrhNSG
        progress: booting...
libvirt: Polkit error : authentication unavailable: no polkit agent available to authenticate action 'org.libvirt.unix.manage'
    finish
        summary: 0 tasks completed
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tmt/cli.py", line 254, in finito
    context.obj.run.go()
  File "/usr/lib/python3.8/site-packages/tmt/base.py", line 909, in go
    plan.go()
  File "/usr/lib/python3.8/site-packages/tmt/base.py", line 503, in go
    step.go()
  File "/usr/lib/python3.8/site-packages/tmt/steps/provision/__init__.py", line 92, in go
    plugin.go()
  File "/usr/lib/python3.8/site-packages/tmt/steps/provision/testcloud.py", line 228, in go
    self._guest.start()
  File "/usr/lib/python3.8/site-packages/tmt/steps/provision/testcloud.py", line 409, in start
    self.instance.spawn_vm()
  File "/usr/lib/python3.8/site-packages/testcloud/instance.py", line 401, in spawn_vm
    conn = libvirt.open(self.connection)
  File "/usr/lib64/python3.8/site-packages/libvirt.py", line 277, in open
    if ret is None:raise libvirtError('virConnectOpen() failed')
libvirt.libvirtError: authentication unavailable: no polkit agent available to authenticate action 'org.libvirt.unix.manage'

$ echo $?
1
```

**Comment by thrix** [comment]
@junaruga that is an interesting error, do you have some special setup? which Fedora are you running please?

We are linking to these docs for the libvirt driver:
https://docs.fedoraproject.org/en-US/quick-docs/getting-started-with-virtualization/

Seems to be some libvirt bug on first look

**Comment by thrix** [comment]
@junaruga seems you are not in `libvirt` group? Seems similar issue reported here: https://bugzilla.redhat.com/show_bug.cgi?id=1437933

**Comment by psss** [comment]
See also the [Virtualization Tips](https://docs.fedoraproject.org/en-US/ci/tmt/#_virtualization_tips) section of the Fedora CI documentation. We should probably add a similar section to the main tmt docs as well.

**Comment by junaruga** [comment]
Hi I am using Fedora 32. And my user is not in `libvirt` group.

**Comment by junaruga** [comment]
Let me try to add the group to my user account and run it again on next Monday 31th August possibly.

Thanks for the checking and tips!

**Comment by junaruga** [comment]
> Let me try to add the group to my user account and run it again on next Monday 31th August possibly.

I added my account to the libvirt group.

```
$ sudo usermod -a -G libvirt jaruga

$ cat /etc/group | grep libvirt
libvirt:x:983:jaruga
```

Then I got the following new error `libvirt.libvirtError: Requested operation is not valid: network 'default' is not active` when running. Do you know what's the reason?

```
$ tmt run -avv execute -h beakerlib
/var/tmp/tmt/run-007
Found 1 plan.

/plans/default
    discover
        how: fmf
        directory: /home/jaruga/git/pkg/fed/tests/ruby
        summary: 2 tests selected
            /run-basic-rails-application
            /systemtap-static-probes-in-ruby
    provision
        how: virtual
        image: fedora
        user: root
        memory: 2048 MB
        disk: 10 GB
        qcow: Fedora-Cloud-Base-32-1.6.x86_64.qcow2
        name: SiuEvoSZIsKaJzex
        progress: booting...
libvirt: Network Driver error : Requested operation is not valid: network 'default' is not active
    finish
        summary: 0 tasks completed
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tmt/cli.py", line 254, in finito
    context.obj.run.go()
  File "/usr/lib/python3.8/site-packages/tmt/base.py", line 909, in go
    plan.go()
  File "/usr/lib/python3.8/site-packages/tmt/base.py", line 503, in go
    step.go()
  File "/usr/lib/python3.8/site-packages/tmt/steps/provision/__init__.py", line 92, in go
    plugin.go()
  File "/usr/lib/python3.8/site-packages/tmt/steps/provision/testcloud.py", line 228, in go
    self._guest.start()
  File "/usr/lib/python3.8/site-packages/tmt/steps/provision/testcloud.py", line 411, in start
    self.instance.start(DEFAULT_BOOT_TIMEOUT)
  File "/usr/lib/python3.8/site-packages/testcloud/instance.py", line 444, in start
    create_status = dom.create()
  File "/usr/lib64/python3.8/site-packages/libvirt.py", line 1234, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: Requested operation is not valid: network 'default' is not active
```

**Comment by junaruga** [comment]
I try to fix seeing [this article](https://blog.programster.org/kvm-missing-default-network) and https://github.com/kubernetes/minikube/issues/828 .

On my machine, it seems that the network "default" is inactive, as the error message said. I do not know why this is happening on my machine.

```
$ sudo virsh net-list --all
 Name      State      Autostart   Persistent
----------------------------------------------
 default   inactive   yes         yes
```

**Comment by junaruga** [comment]
Now it works after activating the network "default" by the following commands!

```
$ sudo virsh net-start default
Network default started

$ sudo virsh net-list --all
 Name      State    Autostart   Persistent
--------------------------------------------
 default   active   yes         yes

$ tmt run -avv execute -h beakerlib
...
total: 2 tests passed

$ echo $?
0
```

I would close this ticket. Thanks for your help.

**Comment by psss** [comment]
@junaruga, thanks for the hint. Good to hear you were able to resolve the issue. I've submitted a documentation update #334 which mentions the network device tip as well.

**Comment by junaruga** [comment]
Sure. Thanks for the update.

**Comment by marques576** [comment]
This solved the issue for me
usermod --append --groups libvirt `whoami`

**Comment by GillesTabary** [comment]
> This solved the issue for me 
> `sudo usermod --append --groups libvirt $(whoami)`

Thanks.
