### ISSUE TITLE
type of `tier` field: import as int or as string?

### ISSUE THREAD

**Issue by t184256** [psss/tmt#358]
[Docs](https://tmt.readthedocs.io/en/latest/spec/tests.html?highlight=tier#tier) send a mixed message regarding the type of the `tier` field:

> Should be a string.
> Examples: `tier: 1`

Nitrate importer results in tier values being strings: `tier: '1'`

Meanwhile `stories/cli/test.fmf` has a example of an arithmetic condition on a tier field: `tmt test show --condition 'tier < 2'`, which assumes it to be an integer.

We should further clarify the typing of `tier`. Personally, I think it's OK to explicitly allow it to be either, fix the nitrate importer to cast to ints and leave those who have string values there without arithmetic conditions. Solidifying is as either int or string and linting for it also seems better than the uncertainty we have now.

**Comment by sopos** [comment]
looks like th eintention was to have it as a int as the condition should work. However, I tried `tmt tests ls --condition 'tier > 0'` and I'm getting following traceback
```
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/tmt/cli.py", line 288, in ls
    for test in context.obj.tree.tests():
  File "/usr/lib/python3.7/site-packages/tmt/base.py", line 714, in tests
    keys=keys, names=names, filters=filters, conditions=conditions)]
  File "/usr/lib/python3.7/site-packages/tmt/base.py", line 713, in <listcomp>
    return [Test(test) for test in self.tree.prune(
  File "/usr/lib/python3.7/site-packages/fmf/base.py", line 379, in prune
    for condition in conditions]):
  File "/usr/lib/python3.7/site-packages/fmf/base.py", line 379, in <listcomp>
    for condition in conditions]):
  File "/usr/lib/python3.7/site-packages/fmf/utils.py", line 168, in evaluate
    return eval(expression)
  File "<string>", line 1, in <module>
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by lukaszachy** [comment]
Thank you for the issue. In the meeting we decided to stick to the string, so I'll update the examples so they are not misleading.

**Comment by sopos** [comment]
It means that the condition will be necessary to write as `tmt tests ls --condition 'int(tier) > 0'`, right?

**Comment by lukaszachy** [comment]
> It means that the condition will be necessary to write as `tmt tests ls --condition 'int(tier) > 0'`, is that right?

Yes, however you need to be sure that all of tests you are trying to filter have number as tier value.
Based on the Tier attribute documentation it doesn't need to be.

**Comment by sopos** [comment]
I prefer tags for this purpose, anyway. But generally I like the Report portal's approach - `key:value` with kind of free form. That lead me to a conclusion it would be nice to allow filtering based on such data model which is achievable by the conditions. We just need to allow to use condition at all relevant levels, I filled it as https://github.com/psss/tmt/issues/373 already.
