### ISSUE TITLE
`tmt` should not run finish step arbitrarily (and discover bug, maybe?)

### ISSUE THREAD

**Issue by pvalena** [psss/tmt#364]
This, f.e., results in recursion:
```console
# I'm in a folder containing this repo
$ mkdir TEST                       # completely empty folder, I'll use like my run ID
$ tmt run --id `readlink -e TEST` -avv plan --name /plans/helps provision -h container prepare -h install -p tmt                                   
//home/lpcs/lpcsf-new/test/tmt/TEST                                                              
Found 1 plan.                                                                                   
                                                                                                
/plans/helps                                                                                    
summary: Check help messages                                                                    
    discover                                                                                    
        how: shell                                                                              
        directory: /home/lpcs/lpcsf-new/test/tmt                                                
    finish                                                                                                                                                                                      
        summary: 0 tasks completed                                                                                                                                                              
Traceback (most recent call last):                                                              
  File "/usr/bin/tmt", line 8, in <module>                                                                                                                                                      
    tmt.cli.main()                                                                              
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__                                                                                                                  
    return self.main(*args, **kwargs)                                                                                                                                                           
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main                                                                                                                      
    rv = self.invoke(ctx)                                                                       
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke                                                                                                                   
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                     
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1290, in invoke                   
    return _process_result(rv)                                                                  
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1224, in _process_result          
    value = ctx.invoke(self.result_callback, value, **ctx.params)                               
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke                                                                                                                    
    return callback(*args, **kwargs)                                                            
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func             
    return f(get_current_context(), *args, **kwargs)                                            
  File "/usr/lib/python3.9/site-packages/tmt/cli.py", line 254, in finito                       
    context.obj.run.go()                                                                                                                                                                        
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 925, in go                                                                                                                          
    plan.go()                                                                                   
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 517, in go                                                                                                                          
    step.go()                                                                                                                                                                                   
  File "/usr/lib/python3.9/site-packages/tmt/steps/discover/__init__.py", line 124, in go                                                                                                       
    plugin.go()                                                                                 
  File "/usr/lib/python3.9/site-packages/tmt/steps/discover/shell.py", line 83, in go
    shutil.copytree(directory, testdir)
  File "/usr/lib64/python3.9/shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib64/python3.9/shutil.py", line 492, in _copytree
    copytree(srcobj, dstname, symlinks, ignore, copy_function,
  File "/usr/lib64/python3.9/shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib64/python3.9/shutil.py", line 492, in _copytree
    copytree(srcobj, dstname, symlinks, ignore, copy_function,
  File "/usr/lib64/python3.9/shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib64/python3.9/shutil.py", line 492, in _copytree
[ . . . ] 
```
**Depth limit reached.**

Nothing was "run". Further analysis: discover has/should have failed, I expect, but it didn't throw an error. In the aftermath, `finish` tries to copy...

```
$ tree TEST
[ . . . ]
│       │   │           │       │   ├── log.txt
│       │   │           │       │   └── step.yaml
│       │   │           │       ├── log.txt
│       │   │           │       └── prepare
│       │   │           │           ├── log.txt
│       │   │           │           └── step.yaml
│       │   │           └── run.yaml
│       │   ├── log.txt
│       │   ├── step.yaml
│       │   └── tests.yaml
│       ├── execute
│       │   ├── log.txt
│       │   ├── results.yaml
│       │   └── step.yaml
│       ├── finish
│       │   ├── log.txt
│       │   └── step.yaml
│       ├── log.txt
│       ├── prepare
│       │   ├── log.txt
│       │   └── step.yaml
│       ├── provision
│       │   ├── guests.yaml
│       │   ├── log.txt
│       │   └── step.yaml
│       └── report
│           ├── log.txt
│           └── step.yaml
└── run.yaml

825 directories, 1817 files
```
Is this a discover bug? Why didn't it fail? (If it would fail, why run `finish`, in this case?)

I'm happy to note, though, using any other folder for "TEST" works (not subfolders).

**Comment by psss** [comment]
Seems to be working fine now:

```
/plan
    discover
        how: fmf
        order: 50
        url: hmmm
        fail: Command 'git clone hmmm /var/tmp/tmt/run-072/plan/discover/default-0/tests' returned 128.
        fail: Command 'git clone hmmm /var/tmp/tmt/run-072/plan/discover/default-0/tests' returned 128.
        fail: Command 'git clone hmmm /var/tmp/tmt/run-072/plan/discover/default-0/tests' returned 128.
    report
        how: display
        order: 50
        summary: no results found
    cleanup
        warn: Nothing to cleanup, no guests provisioned.
```
