### ISSUE TITLE
Check for possible duplicate keys in yaml files

### ISSUE THREAD

**Issue by psss** [psss/tmt#511]
When a user includes a duplicate key in a `yaml` file, parser silently ignores it. This results in confusion which is not easy to sport or detect. It would be nice if `tmt test lint`, `tmt plan lint` and `tmt story lint` check for these duplicates and report error. The following gist might help with implementing this:

* https://gist.github.com/pypt/94d747fe5180851196eb

**Comment by psss** [comment]
See also: https://github.com/yaml/pyyaml/issues/165

**Comment by psss** [comment]
Another option could be to use `python-ruamel-yaml`.

**Comment by thrix** [comment]
Yep, `ruamel.yaml` seems to traceback by default:

```
>>> from ruamel.yaml import YAML
>>> yaml = YAML()
>>> yaml.load("{'a': [1, 2], 'a': [3, 2]}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mvadkert/.cache/pypoetry/virtualenvs/gluetool-modules-siCqN_FE-py2.7/lib/python2.7/site-packages/ruamel/yaml/main.py", line 343, in load
    return constructor.get_single_data()
  File "/home/mvadkert/.cache/pypoetry/virtualenvs/gluetool-modules-siCqN_FE-py2.7/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 113, in get_single_data
    return self.construct_document(node)
  File "/home/mvadkert/.cache/pypoetry/virtualenvs/gluetool-modules-siCqN_FE-py2.7/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 123, in construct_document
    for _dummy in generator:
  File "/home/mvadkert/.cache/pypoetry/virtualenvs/gluetool-modules-siCqN_FE-py2.7/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 1563, in construct_yaml_map
    self.construct_mapping(node, data, deep=True)
  File "/home/mvadkert/.cache/pypoetry/virtualenvs/gluetool-modules-siCqN_FE-py2.7/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 1470, in construct_mapping
    if self.check_mapping_key(node, key_node, maptyp, key, value):
  File "/home/mvadkert/.cache/pypoetry/virtualenvs/gluetool-modules-siCqN_FE-py2.7/lib/python2.7/site-packages/ruamel/yaml/constructor.py", line 295, in check_mapping_key
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "<byte string>", line 1, column 1:
    {'a': [1, 2], 'a': [3, 2]}
    ^ (line: 1)
found duplicate key "a" with value "[3, 2]" (original value: "[1, 2]")
  in "<byte string>", line 1, column 15:
    {'a': [1, 2], 'a': [3, 2]}
                  ^ (line: 1)

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.
```
