### ISSUE TITLE
[RFE] connect last-run with a terminal

### ISSUE THREAD

**Issue by sopos** [psss/tmt#525]
Currently, the  _last-run_ is user-bound. The problem appears if I run two _tmt_ commands from two terminals to a execute multi-host test.

Use-case:
- prepare machines
```
[terminal1]> tmt run -vvvddd --until prepare test --name . provision --how connect --guest host1
[terminal2]> tmt run -vvvddd --until prepare test --name . provision --how connect --guest host2
```
- run test
```
[terminal1]> tmt run -e SERVERS=host1 -e CLIENTS=host2 --last test --name . discover -f execute -f --how tmt --interactive
[terminal2]> tmt run -e SERVERS=host1 -e CLIENTS=host2 --last test --name . discover -f execute -f --how tmt --interactive
```
This should be probably optional so additional switch could be introduced to addintion to _--last_ or completely independent switch _--last-term_.

**Comment by sopos** [comment]
When I tried to workaround it by manually setting _--id_ instead of _--last_ I got following traceback for the second run of the test:
```
/var/tmp/tmt/run-111

/plans/default
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tmt/cli.py", line 283, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 1025, in go
    plan.go()
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 570, in go
    step.wake()
  File "/usr/lib/python3.9/site-packages/tmt/steps/execute/__init__.py", line 87, in wake
    super().wake()
  File "/usr/lib/python3.9/site-packages/tmt/steps/__init__.py", line 121, in wake
    self._workdir_cleanup()
  File "/usr/lib/python3.9/site-packages/tmt/utils.py", line 480, in _workdir_cleanup
    shutil.rmtree(directory)
  File "/usr/lib64/python3.9/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.9/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.9/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.9/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 4 more times]
  File "/usr/lib64/python3.9/shutil.py", line 659, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib64/python3.9/shutil.py", line 657, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: '.ssh'
```

**Comment by sopos** [comment]
apparently this is connected to copying the beakerlib backup directory (https://github.com/psss/tmt/issues/502)
