### ISSUE TITLE
Ugly traceback when tmt test convert is used with tcms/bzilla plugin and kerberos ticket expires

### ISSUE THREAD

**Issue by marmolak** [psss/tmt#57]
Hello.

Just ordinary used of tmt test convert leads to very not nice traceback when kerberos ticket expires.

How to reproduce:
# leave krb ticket to expire
$ cd tuned/Regression/Verification-of-sysctll-is-broken-for-tabs
$ tmt test convert

Result:
Checking the '/home/rhack/git/tests/tuned/Regression/Verification-of-sysctll-is-broken-for-tabs' directory.
Makefile found in '/home/rhack/git/tests/tuned/Regression/Verification-of-sysctll-is-broken-for-tabs/Makefile'.
test: /CoreOS/tuned/Regression/Verification-of-sysctll-is-broken-for-tabs
description: Test for BZ#1711230 (Verification of sysctll is broken for tabs)
component: tuned
duration: 20m
Purpose found in '/home/rhack/git/tests/tuned/Regression/Verification-of-sysctll-is-broken-for-tabs/PURPOSE'.
description:
Bug summary: Verification of sysctll is broken for tabs
Bugzilla link: https://bugzilla.redhat.com/show_bug.cgi?id=1711230
Nitrate Traceback (most recent call last):
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/nitrate/base.py", line 200, in _server
    Config().nitrate.username,
AttributeError: 'Section' object has no attribute 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/nitrate/xmlrpc_driver.py", line 105, in single_request_with_cookies
    h = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1267, in send_request
    connection = self.make_connection(host)
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/nitrate/xmlrpc_driver.py", line 185, in make_connection
    chost, self._extra_headers, x509 = self.get_host_info(host)
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/nitrate/xmlrpc_driver.py", line 163, in get_host_info
    response = vc.step()
  File "</home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/decorator.py:decorator-gen-15>", line 2, in step
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/gssapi/_utils.py", line 167, in check_last_err
    return func(self, *args, **kwargs)
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/gssapi/sec_contexts.py", line 521, in step                     [23/169]
    return self._initiator_step(token=token)
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/gssapi/sec_contexts.py", line 542, in _initiator_step
    token)
  File "gssapi/raw/sec_contexts.pyx", line 245, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639053): No Kerb
eros credentials available (default cache: KEYRING:persistent:20787)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rhack/.virtualenvs/tmt/bin/tmt", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/rhack/tmt/bin/tmt", line 11, in <module>
    tmt.cli.main()
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rhack/tmt/tmt/cli.py", line 418, in convert
    data = tmt.convert.read(path, makefile, nitrate, purpose)
  File "/home/rhack/tmt/tmt/convert.py", line 108, in read
    testcases = list(TestCase.search(script=test))
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/nitrate/mutable.py", line 912, in search
    for inject in Nitrate()._server.TestCase.filter(dict(query))]
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/nitrate/base.py", line 206, in _server
    Config().nitrate.url).server
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/nitrate/xmlrpc_driver.py", line 443, in __init__
    login_dict = self.do_command("Auth.login_krbv", [])
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/nitrate/xmlrpc_driver.py", line 393, in do_command
    return getattr(self.server, verb)(*params)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/rhack/.virtualenvs/tmt/lib/python3.7/site-packages/nitrate/xmlrpc_driver.py", line 137, in single_request_with_cookies
    h.close()
UnboundLocalError: local variable 'h' referenced before assignment

Which basically says: you don't have kerberos ticket! :)

Should return smaller amount of words :).

Thank you for your time.

**Comment by pvalena** [comment]
I usually check for KT like so:
```
klist -a | grep -q "${login_at_domain}$"
```

**Comment by marmolak** [comment]
Yeah. I know that my ticket is expired.

klist: Credentials cache keyring 'persistent:20787:20787' not found

**Comment by marmolak** [comment]
It works after kinit :).

**Comment by pvalena** [comment]
> Yeah. I know that my ticket is expired.

Well I meant in a program... `0 -> OK` `1 -> expired`
