### ISSUE TITLE
traceback for --help

### ISSUE THREAD

**Issue by pirat89** [psss/tmt#615]
```
#  tmt run plans --condition --help
tmt run plans --condition --help
/var/tmp/tmt/run-077
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tmt/cli.py", line 291, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 1114, in go
    if not self.plans:
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 1008, in plans
    self._plans = self.tree.plans(run=self)
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 879, in plans
    return self._filters_conditions(
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 812, in _filters_conditions
    if not all([fmf.utils.evaluate(condition, cond_vars, node)
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 812, in <listcomp>
    if not all([fmf.utils.evaluate(condition, cond_vars, node)
  File "/usr/lib/python3.9/site-packages/fmf/utils.py", line 168, in evaluate
    return eval(expression)
  File "<string>", line 1, in <module>
TypeError: bad operand type for unary -: '_Helper'

```

**Comment by FrNecas** [comment]
There is probably not much we can do about this :/ `--condition` requires one argument, click takes whatever is there so in this case `--help` and passes it to tmt. The given condition is then used in `eval()` and it evaluates as Python code which can be anything so basically any exception can be thrown. The exception should probably be caught so that it doesn't traceback but that should probably be handled on fmf side. Currently only NameError and KeyError are caught so perhaps a general `Exception` should be caught as well to avoid these ugly tracebacks?

**Comment by lukaszachy** [comment]
Well, you can feed condition with some nonsense even intentionally so I'd say catching Exception from eval and presenting it to the user nicely is a must.

It will not help with this case, but at least user will get a hint that some option is  taken as --condition value
