### ISSUE TITLE
tmt run workdir init is not thread safe

### ISSUE THREAD

**Issue by thrix** [psss/tmt#659]
While implementing a related feature, I found out that tmt run is not thread safe, it can happen two tmt runs will fight for the same run id.

Filing as an issue so I can fix later.

```
for i in {1..100}; do (tmt run --dry &); done | grep '/var/tmp'
/var/tmp/tmt/run-042
/var/tmp/tmt/run-043
/var/tmp/tmt/run-044
/var/tmp/tmt/run-045
/var/tmp/tmt/run-046
/var/tmp/tmt/run-047
/var/tmp/tmt/run-048
/var/tmp/tmt/run-049
/var/tmp/tmt/run-050
/var/tmp/tmt/run-051
/var/tmp/tmt/run-052
/var/tmp/tmt/run-053
/var/tmp/tmt/run-054
/var/tmp/tmt/run-056
/var/tmp/tmt/run-055
/var/tmp/tmt/run-058
/var/tmp/tmt/run-057
/var/tmp/tmt/run-059
/var/tmp/tmt/run-060
/var/tmp/tmt/run-061
/var/tmp/tmt/run-062
/var/tmp/tmt/run-063
/var/tmp/tmt/run-064
/var/tmp/tmt/run-065
/var/tmp/tmt/run-066
/var/tmp/tmt/run-067
/var/tmp/tmt/run-068
/var/tmp/tmt/run-069
/var/tmp/tmt/run-070
/var/tmp/tmt/run-071
/var/tmp/tmt/run-071
/var/tmp/tmt/run-072
/var/tmp/tmt/run-074
/var/tmp/tmt/run-076
/var/tmp/tmt/run-073
/var/tmp/tmt/run-075
/var/tmp/tmt/run-077
/var/tmp/tmt/run-078
/var/tmp/tmt/run-079
Traceback (most recent call last):
  File "/home/mvadkert/.local/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1239, in invoke
    return _process_result([])
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/cli.py", line 280, in finito
    click_context.obj.run.go()
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/base.py", line 973, in go
    plan.go()
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/base.py", line 555, in go
    step.go()
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/steps/discover/__init__.py", line 125, in go
    plugin.go()
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/steps/discover/shell.py", line 85, in go
    os.makedirs(testdir)
  File "/usr/lib64/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/var/tmp/tmt/run-071/plans/default/discover/default/tests'
/var/tmp/tmt/run-081
/var/tmp/tmt/run-080
/var/tmp/tmt/run-082
/var/tmp/tmt/run-083
/var/tmp/tmt/run-082
/var/tmp/tmt/run-086
/var/tmp/tmt/run-084
/var/tmp/tmt/run-085
/var/tmp/tmt/run-087
[Errno 17] File exists: '/var/tmp/tmt/run-089' -> '/home/mvadkert/.config/tmt/last-run'
/var/tmp/tmt/run-088
/var/tmp/tmt/run-090
/var/tmp/tmt/run-091
/var/tmp/tmt/run-092
Traceback (most recent call last):
  File "/home/mvadkert/.local/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1239, in invoke
    return _process_result([])
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/cli.py", line 280, in finito
    click_context.obj.run.go()
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/base.py", line 973, in go
    plan.go()
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/base.py", line 555, in go
    step.go()
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/steps/discover/__init__.py", line 125, in go
    plugin.go()
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/steps/discover/shell.py", line 85, in go
    os.makedirs(testdir)
  File "/usr/lib64/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/var/tmp/tmt/run-082/plans/default/discover/default/tests'
/var/tmp/tmt/run-093
/var/tmp/tmt/run-094
/var/tmp/tmt/run-095
/var/tmp/tmt/run-096
/var/tmp/tmt/run-097
/var/tmp/tmt/run-099
/var/tmp/tmt/run-098
/var/tmp/tmt/run-101
/var/tmp/tmt/run-101
/var/tmp/tmt/run-100
/var/tmp/tmt/run-102
/var/tmp/tmt/run-103
/var/tmp/tmt/run-104
/var/tmp/tmt/run-105
/var/tmp/tmt/run-107
/var/tmp/tmt/run-106
/var/tmp/tmt/run-108
/var/tmp/tmt/run-109
/var/tmp/tmt/run-111
/var/tmp/tmt/run-110
/var/tmp/tmt/run-112
/var/tmp/tmt/run-114
/var/tmp/tmt/run-115
/var/tmp/tmt/run-113
/var/tmp/tmt/run-116
Traceback (most recent call last):
  File "/home/mvadkert/.local/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1239, in invoke
    return _process_result([])
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
/var/tmp/tmt/run-117
  File "/usr/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/cli.py", line 280, in finito
    click_context.obj.run.go()
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/base.py", line 973, in go
    plan.go()
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/base.py", line 555, in go
    step.go()
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/steps/discover/__init__.py", line 125, in go
    plugin.go()
  File "/home/mvadkert/.local/lib/python3.7/site-packages/tmt/steps/discover/shell.py", line 85, in go
    os.makedirs(testdir)
  File "/usr/lib64/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/var/tmp/tmt/run-101/plans/default/discover/default/tests'
/var/tmp/tmt/run-118
/var/tmp/tmt/run-119
/var/tmp/tmt/run-120
/var/tmp/tmt/run-121
/var/tmp/tmt/run-122
/var/tmp/tmt/run-123
/var/tmp/tmt/run-125
/var/tmp/tmt/run-128
/var/tmp/tmt/run-126
/var/tmp/tmt/run-127
/var/tmp/tmt/run-124
/var/tmp/tmt/run-130
/var/tmp/tmt/run-129
[Errno 17] File exists: '/var/tmp/tmt/run-131' -> '/home/mvadkert/.config/tmt/last-run'
/var/tmp/tmt/run-132
/var/tmp/tmt/run-133
/var/tmp/tmt/run-135
/var/tmp/tmt/run-134
/var/tmp/tmt/run-136
/var/tmp/tmt/run-137
/var/tmp/tmt/run-138
```

**Comment by RHEmployee** [comment]
Hello. Seems like this is still a issue. I'm currently working on locking for minute plugin so maybe upstream tool for simple locking would be nice. 
But it depends on in which state is parallelization of tmt.

**Comment by RHEmployee** [comment]
Hi. I'm not sure about state of work on tmt in threads (parallel tmt) but this should be solved by 2:

1) try to win a race by checking result of mkdir - not much sane
2) use filelock (which is now dependency for minute plugin).

Do you think this should be solved before tmt reaches full parallel approach?

**Comment by lukaszachy** [comment]
IMHO it can be done without locking  - just retry with next candidate (higher run) after `os.makedirs` failed until max allowed number or success

**Comment by lukaszachy** [comment]
@thrix After some time exception changed a bit. But it is again in shell's go.
```
$ for i in {1..100}; do (tmt run >/dev/null &); done
$ Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1638, in invoke
    return _process_result([] if self.chain else None)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1628, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/tmt/cli.py", line 384, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.10/site-packages/tmt/base.py", line 1822, in go
    plan.go()
  File "/usr/lib/python3.10/site-packages/tmt/base.py", line 1040, in go
    step.go()
  File "/usr/lib/python3.10/site-packages/tmt/steps/discover/__init__.py", line 154, in go
    phase.go()
  File "/usr/lib/python3.10/site-packages/tmt/steps/discover/shell.py", line 102, in go
    os.symlink(relative_path, testdir)
FileExistsError: [Errno 17] File exists: '../../tree' -> '/var/tmp/tmt/run-185/plans/default/discover/default/tests'
```

Plan used
```
execute:
  how: tmt
provision:
  how: container
discover:
  how: shell
  tests:
  - test: ls
    name: foo`
```
