### ISSUE TITLE
`tmt run -l finish` crashes: Failed to connect socket to '/var/run/libvirt/libvirt-sock-ro': No such file or directory

### ISSUE THREAD

**Issue by martinpitt** [psss/tmt#681]
I am running the pre-view tmt with the copr packages from https://github.com/psss/tmt/pull/642:

testcloud-0.5.0-1.fc33.noarch
tmt-1.3.1-2.fc33.noarch

With that, doing a complete run works fine, but a separate cleanup step after e.g. `--until report` crashes. Simplest reproducer:

    tmt run provision --how virtual --image fedora-33
    tmt run -l login  # this works fine
    tmt run -l finish

This crashes with
```
libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/libvirt-sock-ro': No such file or directory
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tmt/cli.py", line 291, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 1121, in go
    plan.go()
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 614, in go
    self.finish.go()
  File "/usr/lib/python3.9/site-packages/tmt/steps/finish/__init__.py", line 69, in go
    guest.stop()
  File "/usr/lib/python3.9/site-packages/tmt/steps/provision/testcloud.py", line 456, in stop
    self.instance.stop()
  File "/usr/lib/python3.9/site-packages/testcloud/instance.py", line 598, in stop
    domain_state = _find_domain(self.name, self.connection)
  File "/usr/lib/python3.9/site-packages/testcloud/instance.py", line 109, in _find_domain
    conn = libvirt.openReadOnly(connection)
  File "/usr/lib64/python3.9/site-packages/libvirt.py", line 290, in openReadOnly
    if ret is None:raise libvirtError('virConnectOpenReadOnly() failed')
libvirt.libvirtError: Failed to connect socket to '/var/run/libvirt/libvirt-sock-ro': No such file or directory
```

i.e. this is trying to talk to qemu:///system instead of  qemu:///session. After that, the machine is still running:

```
❱❱❱ virsh list
 Id   Name               State
----------------------------------
 2    TKJauGrKOjoRKveO   running
```

I can clean this up manually with virsh destroy/undefine and `rm -rf /var/tmp/tmt/run* /var/tmp/tmt/testcloud/instances/`.

**Comment by psss** [comment]
>  tmt-1.3.1-2.fc33.noarch

This does not seem to be the proper package from copr. I've tested the above-mentioned scenario with the latest content from master and it works fine.

Could you please try with [this copr repo](https://copr.fedorainfracloud.org/coprs/packit/psss-tmt-687/build/2115861/)? I believe, the error you reported has been already fixed and the copr repo above contains one more fix related to this. Thanks.

**Comment by martinpitt** [comment]
Confirmed, thank you! Works fine with tmt-1.3.1-1.20210406121211996945.pr687.74.g84a43ee.fc33.noarch.

I honestly have no idea any more where I got 1.3.1-2.fc33 from, but if it wasn't from updates, I only downloaded some rpms from copr recently.

**Comment by psss** [comment]
Good to hear, thanks for the update.
