### ISSUE TITLE
tmt tests export --nitrate --general traces back

### ISSUE THREAD

**Issue by sopos** [psss/tmt#690]
`tmt tests export --nitrate --general` traces back if the _TC_ is already linked to the _general plan_.
```
$ tmt tests export --nitrate --create --general .
Test case 'TC#0610070' found.
summary: /rsyslog/Regression/bz1944718-large-group
script: /rsyslog/Regression/bz1944718-large-group
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tmt/cli.py", line 509, in export
    test.export(format_='nitrate')
  File "/usr/lib/python3.9/site-packages/tmt/base.py", line 420, in export
    tmt.export.export_to_nitrate(self)
  File "/usr/lib/python3.9/site-packages/tmt/export.py", line 216, in export_to_nitrate
    for nitrate_plan in nitrate_case.testplans:
  File "/usr/lib/python3.9/site-packages/nitrate/containers.py", line 137, in __iter__
    for item in self._items:
RuntimeError: Set changed size during iteration
```
I think this is a regression as I do not remember seeing such behavior.

**Comment by jscotka** [comment]
https://github.com/psss/tmt/pull/691 should fix this issue

**Comment by sopos** [comment]
I can confirm the https://github.com/psss/tmt/pull/691 fixes this issue.
