### ISSUE TITLE
TypeError crash when `ref:` is an int

### ISSUE THREAD

**Issue by martinpitt** [psss/tmt#790]
In an (internal, sorry) PR against RHEL, the Testing Farm result [crashed like this](http://artifacts.osci.redhat.com/testing-farm/61687298-1646-441a-83b5-9f16ace835da/):
```
# STDOUT:
---v---v---v---v---v---
/ARTIFACTS/work-upstreamcckpT1
Found 1 plan.

/plans/upstream
    discover
        how: fmf
        url: https://github.com/cockpit-project/cockpit-machines
        ref: 244
    finish
        summary: 0 tasks completed

---^---^---^---^---^---

# STDERR:
---v---v---v---v---v---
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tmt/cli.py", line 297, in finito
    click_context.obj.run.go()
  File "/usr/lib/python3.8/site-packages/tmt/base.py", line 1368, in go
    plan.go()
  File "/usr/lib/python3.8/site-packages/tmt/base.py", line 763, in go
    step.go()
  File "/usr/lib/python3.8/site-packages/tmt/steps/discover/__init__.py", line 127, in go
    plugin.go()
  File "/usr/lib/python3.8/site-packages/tmt/steps/discover/fmf.py", line 160, in go
    self.run(['git', 'checkout', '-f', ref], cwd=testdir, shell=False)
  File "/usr/lib/python3.8/site-packages/tmt/utils.py", line 401, in run
    line = ' '.join(command)
TypeError: sequence item 3: expected str instance, int found

---^---^---^---^---^---
```

It seems that tmt currently expects the plan's `ref:` to be a string, but when specifying a version tag name "244", YAML parses that as an integer. Can you please wrap this in `str(ref)` so that an integer works as well? That'd be friendlier than this crash.

Thank you!

**Comment by psss** [comment]
Thanks for reporting this, should be fixed by #793.
