### ISSUE TITLE
Traceback when podman is not installed

### ISSUE THREAD

**Issue by RHEmployee** [psss/tmt#822]
$ tmt run provision -h container -vv -ddd

/var/tmp/tmt/run-028

/plans/features/advanced
        Read file '/var/tmp/tmt/run-028/plans/features/advanced/provision/step.yaml'.
        Step data not found.
        Read file '/var/tmp/tmt/run-028/plans/features/advanced/provision/guests.yaml'.
        Provisioned guests not found.
        Using the 'ProvisionPodman' plugin for the 'container' method.
        status: todo
        Write file '/var/tmp/tmt/run-028/plans/features/advanced/provision/step.yaml'.
        Write file '/var/tmp/tmt/run-028/plans/features/advanced/provision/guests.yaml'.
    provision
        workdir: /var/tmp/tmt/run-028/plans/features/advanced/provision
        how: container
        image: fedora
            Check for container image 'fedora'.
Traceback (most recent call last):
  File "/home/brmbrm/devel/tmt/./bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/brmbrm/devel/tmt/tmt/cli.py", line 300, in finito
    click_context.obj.run.go()
  File "/home/brmbrm/devel/tmt/tmt/base.py", line 1404, in go
    plan.go()
  File "/home/brmbrm/devel/tmt/tmt/base.py", line 765, in go
    step.go()
  File "/home/brmbrm/devel/tmt/tmt/steps/provision/__init__.py", line 95, in go
    plugin.go()
  File "/home/brmbrm/devel/tmt/tmt/steps/provision/podman.py", line 92, in go
    self._guest.start()
  File "/home/brmbrm/devel/tmt/tmt/steps/provision/podman.py", line 136, in start
    image_id = self.podman(
  File "/home/brmbrm/devel/tmt/tmt/steps/provision/podman.py", line 192, in podman
    return self.run(['podman'] + command, shell=False, **kwargs)
  File "/home/brmbrm/devel/tmt/tmt/utils.py", line 420, in run
    return self._run(
  File "/home/brmbrm/devel/tmt/tmt/utils.py", line 308, in _run
    process = subprocess.Popen(
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'podman'

**Comment by FrNecas** [comment]
This probably won't happen when using the `tmt` package (the podman module requires podman package) but good point that it may be confusing when developing/using tmt from source code. Will be an easy fix
