### ISSUE TITLE
Environment-file doesn't work when using url

### ISSUE THREAD

**Issue by kokesak** [psss/tmt#897]
In convert2rhel CI we need to pass environment file via URL, which fails on the following traceback:
```
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 721, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1065, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1065, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 894, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tmt/cli.py", line 576, in ls
    for plan in context.obj.tree.plans():
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 1149, in plans
    for plan in self.tree.prune(keys=keys, names=names)],
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 1149, in <listcomp>
    for plan in self.tree.prune(keys=keys, names=names)],
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 486, in __init__
    self._environment = self._get_environment_vars(node)
  File "/usr/lib/python3.6/site-packages/tmt/base.py", line 552, in _get_environment_vars
    environment_files, root=node.root)
  File "/usr/lib/python3.6/site-packages/tmt/utils.py", line 804, in environment_file_to_dict
    if Path(full_path).suffix in (".yaml", ".yml"):
UnboundLocalError: local variable 'full_path' referenced before assignment
```
http://pastebin.test.redhat.com/995715

The issue is that the variable `full_path` is defined in an `else` statement which happens only when using local environment file (https://github.com/psss/tmt/blob/master/tmt/utils.py#L802)

**Comment by psss** [comment]
Hi! Thanks for reporting this. The issue has been fixed in #881 and is available in the latest `tmt` from the [copr](https://copr.fedorainfracloud.org/coprs/psss/tmt/) repository. Could you try it from there?

**Comment by psss** [comment]
Temporary workaround:

```yaml
environment-file:
  - dummy.yaml
  - https://example.org/variables.yaml
```

**Comment by kokesak** [comment]
Thanks @psss, closing as it is duplicate.
